// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace NewFLD
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"N_LEar_X")]
            public float N_LEar_X { get; set; }

            [ColumnName(@"N_LEar_Y")]
            public float N_LEar_Y { get; set; }

            [ColumnName(@"REar_REye_X")]
            public float REar_REye_X { get; set; }

            [ColumnName(@"REar_REye_Y")]
            public float REar_REye_Y { get; set; }

            [ColumnName(@"LEye_LEar_X")]
            public float LEye_LEar_X { get; set; }

            [ColumnName(@"LEye_LEar_Y")]
            public float LEye_LEar_Y { get; set; }

            [ColumnName(@"REye_N_X")]
            public float REye_N_X { get; set; }

            [ColumnName(@"REye_N_Y")]
            public float REye_N_Y { get; set; }

            [ColumnName(@"N_LEye_X")]
            public float N_LEye_X { get; set; }

            [ColumnName(@"N_+Eye_Y")]
            public float N__Eye_Y { get; set; }

            [ColumnName(@"FLD")]
            public string FLD { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"N_LEar_X")]
            public float N_LEar_X { get; set; }

            [ColumnName(@"N_LEar_Y")]
            public float N_LEar_Y { get; set; }

            [ColumnName(@"REar_REye_X")]
            public float REar_REye_X { get; set; }

            [ColumnName(@"REar_REye_Y")]
            public float REar_REye_Y { get; set; }

            [ColumnName(@"LEye_LEar_X")]
            public float LEye_LEar_X { get; set; }

            [ColumnName(@"LEye_LEar_Y")]
            public float LEye_LEar_Y { get; set; }

            [ColumnName(@"REye_N_X")]
            public float REye_N_X { get; set; }

            [ColumnName(@"REye_N_Y")]
            public float REye_N_Y { get; set; }

            [ColumnName(@"N_LEye_X")]
            public float N_LEye_X { get; set; }

            [ColumnName(@"N_+Eye_Y")]
            public float N__Eye_Y { get; set; }

            [ColumnName(@"FLD")]
            public uint FLD { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        public static string MLNetModelPath = Path.GetFullPath("MLModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
